extends SceneTree
const Controller = preload("res://scripts/geodot_hlod_controller.gd")
func _init() -> void:
	var c = Controller.new()
	c.configure_regions(["a", "b", "c"])
	c.request_detail("a", 4, 100)
	c.request_detail("b", 4, 100)
	c.mark_detail_ready("b", 4, 100)
	assert(c.coverage_holes().is_empty())
	assert(c.duplicate_owners().is_empty())
	c.prefer_base("b")
	c.request_detail("c", 4, 100)
	assert(c.coverage_holes().is_empty())
	assert(c.duplicate_owners().is_empty())
	print("GEODOT_HLOD_PAN=PASS holes=0 duplicate_owners=0")
	quit(0)
