extends RefCounted

## Offline GPS search index independent of UI, routing and rendering.
##
## Dependencies:
## - Reads portable BSI1 JSONL generated by tools/build_search_index.py.
## - Returns plain dictionaries with id/kind/display/subtitle/x/y/score.
## - Keeps matching deterministic and aligned with the Python reference implementation.

var _records: Array[Dictionary] = []

func load_file(path: String) -> Dictionary:
	_records.clear()
	if not FileAccess.file_exists(path):
		return {"success": false, "error": "missing_index", "count": 0}
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return {"success": false, "error": "open_failed", "count": 0}
	if file.eof_reached():
		return {"success": false, "error": "empty_index", "count": 0}
	var header_value: Variant = JSON.parse_string(file.get_line())
	if typeof(header_value) != TYPE_DICTIONARY:
		return {"success": false, "error": "bad_header", "count": 0}
	var header: Dictionary = header_value as Dictionary
	if str(header.get("format", "")) != "BSI1":
		return {"success": false, "error": "bad_format", "count": 0}
	while not file.eof_reached():
		var line: String = file.get_line().strip_edges()
		if line.is_empty():
			continue
		var value: Variant = JSON.parse_string(line)
		if typeof(value) != TYPE_DICTIONARY:
			return {"success": false, "error": "bad_record", "count": 0}
		var item: Dictionary = value as Dictionary
		_records.append({
			"id": str(item.get("id", "")),
			"kind": str(item.get("kind", "")),
			"display": str(item.get("display", "")),
			"subtitle": str(item.get("subtitle", "")),
			"x": float(item.get("x", 0.0)),
			"y": float(item.get("y", 0.0)),
			"search": str(item.get("search", "")),
		})
	var expected_count: int = int(header.get("count", -1))
	if expected_count != _records.size():
		_records.clear()
		return {"success": false, "error": "count_mismatch", "count": 0}
	_records.sort_custom(func(a: Dictionary, b: Dictionary) -> bool: return str(a["id"]) < str(b["id"]))
	return {"success": true, "error": "", "count": _records.size()}

func count() -> int:
	return _records.size()

func search(query: String, limit: int = 8) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	if limit <= 0:
		return result
	var normalized: String = normalize_search_text(query)
	if normalized.is_empty():
		return result
	var query_tokens: PackedStringArray = normalized.split(" ", false)
	for record in _records:
		var display: String = normalize_search_text(str(record.get("display", "")))
		var haystack: String = str(record.get("search", ""))
		if haystack.is_empty():
			haystack = normalize_search_text("%s %s" % [record.get("display", ""), record.get("subtitle", "")])
		var score: Array = _match_score(normalized, query_tokens, haystack, display, str(record.get("id", "")))
		if score.is_empty():
			continue
		var item: Dictionary = record.duplicate()
		item["score"] = score
		result.append(item)
	result.sort_custom(_result_less)
	if result.size() > limit:
		result.resize(limit)
	return result

static func normalize_search_text(value: String) -> String:
	var text: String = value.to_lower()
	var replacements: Dictionary = {
		"å": "a", "ä": "a", "á": "a", "à": "a", "â": "a", "ã": "a",
		"ö": "o", "ó": "o", "ò": "o", "ô": "o", "õ": "o",
		"é": "e", "è": "e", "ê": "e", "ë": "e",
		"í": "i", "ì": "i", "î": "i", "ï": "i",
		"ú": "u", "ù": "u", "û": "u", "ü": "u",
		"ý": "y", "ÿ": "y", "æ": "ae", "ø": "o", "ß": "ss",
	}
	for key in replacements:
		text = text.replace(str(key), str(replacements[key]))
	var parts: PackedStringArray = PackedStringArray()
	var current: String = ""
	for index in range(text.length()):
		var character: String = text.substr(index, 1)
		var code: int = character.unicode_at(0)
		var allowed: bool = (code >= 48 and code <= 57) or (code >= 97 and code <= 122)
		if allowed:
			current += character
		elif not current.is_empty():
			parts.append(current)
			current = ""
	if not current.is_empty():
		parts.append(current)
	return " ".join(parts)

static func _match_score(query: String, query_tokens: PackedStringArray, haystack: String, display: String, record_id: String) -> Array:
	var display_words: PackedStringArray = display.split(" ", false)
	var all_words: PackedStringArray = haystack.split(" ", false)
	var tier: int = -1
	if query == display:
		tier = 0
	elif display.begins_with(query):
		tier = 1
	elif _all_tokens_prefix(query_tokens, display_words):
		tier = 2
	elif display.contains(query):
		tier = 3
	elif _all_tokens_prefix(query_tokens, all_words):
		tier = 4
	elif haystack.contains(query):
		tier = 5
	else:
		return []
	return [tier, maxi(0, display.length() - query.length()), display.length(), record_id]

static func _all_tokens_prefix(tokens: PackedStringArray, words: PackedStringArray) -> bool:
	if tokens.is_empty():
		return false
	for token in tokens:
		var found: bool = false
		for word in words:
			if word.begins_with(token):
				found = true
				break
		if not found:
			return false
	return true

static func _result_less(a: Dictionary, b: Dictionary) -> bool:
	var left: Array = a.get("score", []) as Array
	var right: Array = b.get("score", []) as Array
	for index in range(mini(left.size(), right.size())):
		if left[index] == right[index]:
			continue
		return left[index] < right[index]
	return left.size() < right.size()
