class_name RoadSurfaceQuery
extends RefCounted

## Classifies world positions against authoritative BRT1 road centerlines using lazily cached spatial bins.
##
## Dependencies:
## - Reads read-only LOD2 BRT1 runtime tiles generated by the world-data pipeline.
## - Uses the shared WorldCoordinates owner; has no rendering, vehicle, routing-policy, or SceneTree dependency.

const ROAD_MAGIC: String = "BRT1"
const ROAD: StringName = &"road"
const OFF_ROAD: StringName = &"off_road"
const QUERY_LOD: int = 2
const BIN_SIZE_M: float = 128.0

var _world_dir: String = ""
var _world_coordinates
var _tile_cache: Dictionary = {}
var _perf_queries: int = 0
var _perf_segments_checked: int = 0
var _perf_index_entries: int = 0
var _perf_bins_built: int = 0

func setup(world_dir: String, world_coordinates) -> void:
	_world_dir = world_dir
	_world_coordinates = world_coordinates
	_tile_cache.clear()
	_perf_queries = 0
	_perf_segments_checked = 0
	_perf_index_entries = 0
	_perf_bins_built = 0

func surface_at(world_position: Vector3) -> StringName:
	if _world_coordinates == null or _world_dir.is_empty():
		return OFF_ROAD
	_perf_queries += 1
	var tile: Vector2i = _world_coordinates.world_to_tile(world_position)
	var absolute_position: Vector2 = _world_coordinates.world_to_absolute(world_position)
	for ty in range(tile.y - 1, tile.y + 2):
		for tx in range(tile.x - 1, tile.x + 2):
			if _tile_contains_road(Vector2i(tx, ty), absolute_position):
				return ROAD
	return OFF_ROAD

func consume_perf_metrics() -> Dictionary:
	var result := {
		"queries": _perf_queries,
		"segments_checked": _perf_segments_checked,
		"index_entries": _perf_index_entries,
		"bins_built": _perf_bins_built,
	}
	_perf_queries = 0
	_perf_segments_checked = 0
	_perf_index_entries = 0
	_perf_bins_built = 0
	return result

func _tile_contains_road(tile: Vector2i, absolute_position: Vector2) -> bool:
	var candidates: Array = _segments_for_point(tile, absolute_position)
	for segment_value in candidates:
		var segment: Dictionary = segment_value as Dictionary
		_perf_segments_checked += 1
		var a: Vector2 = segment["a"] as Vector2
		var b: Vector2 = segment["b"] as Vector2
		var half_width_m: float = float(segment["half_width_m"])
		if _distance_to_segment(absolute_position, a, b) <= half_width_m:
			return true
	return false

func _segments_for_point(tile: Vector2i, absolute_position: Vector2) -> Array:
	var tile_data: Dictionary = _tile_data(tile)
	var bins: Dictionary = tile_data["bins"] as Dictionary
	var origin: Vector2 = _world_coordinates.tile_origin_absolute(tile)
	var cell: Vector2i = _bin_for_point(absolute_position, origin)
	if bins.has(cell):
		return bins[cell] as Array
	var bucket: Array = []
	var cell_min := origin + Vector2(float(cell.x), float(cell.y)) * BIN_SIZE_M
	var cell_max := cell_min + Vector2.ONE * BIN_SIZE_M
	for segment_value in tile_data["segments"] as Array:
		var segment: Dictionary = segment_value as Dictionary
		if _segment_expanded_aabb_intersects_cell(segment, cell_min, cell_max):
			bucket.append(segment)
			_perf_index_entries += 1
	bins[cell] = bucket
	_perf_bins_built += 1
	return bucket

func _tile_data(tile: Vector2i) -> Dictionary:
	if _tile_cache.has(tile):
		return _tile_cache[tile] as Dictionary
	var result := {"segments": [], "bins": {}}
	var segments: Array = result["segments"] as Array
	var path: String = "%s/lod%d/%d_%d.brtile" % [_world_dir, QUERY_LOD, tile.x, tile.y]
	if not FileAccess.file_exists(path):
		_tile_cache[tile] = result
		return result
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null or file.get_length() < 8:
		_tile_cache[tile] = result
		return result
	if file.get_buffer(4).get_string_from_ascii() != ROAD_MAGIC:
		_tile_cache[tile] = result
		return result
	var count: int = file.get_32()
	var origin: Vector2 = _world_coordinates.tile_origin_absolute(tile)
	for _index in range(count):
		var road_class: int = file.get_8()
		var a := origin + Vector2(file.get_float(), file.get_float())
		var b := origin + Vector2(file.get_float(), file.get_float())
		segments.append({"a": a, "b": b, "half_width_m": _road_half_width_m(road_class)})
	_tile_cache[tile] = result
	return result

func _segment_expanded_aabb_intersects_cell(segment: Dictionary, cell_min: Vector2, cell_max: Vector2) -> bool:
	var a: Vector2 = segment["a"] as Vector2
	var b: Vector2 = segment["b"] as Vector2
	var half_width_m: float = float(segment["half_width_m"])
	var segment_min := Vector2(minf(a.x, b.x) - half_width_m, minf(a.y, b.y) - half_width_m)
	var segment_max := Vector2(maxf(a.x, b.x) + half_width_m, maxf(a.y, b.y) + half_width_m)
	return segment_max.x >= cell_min.x and segment_min.x <= cell_max.x and segment_max.y >= cell_min.y and segment_min.y <= cell_max.y

func _bin_for_point(point: Vector2, origin: Vector2) -> Vector2i:
	var local := point - origin
	return Vector2i(floori(local.x / BIN_SIZE_M), floori(local.y / BIN_SIZE_M))

func _road_half_width_m(road_class: int) -> float:
	if road_class <= 3:
		return 7.0
	if road_class <= 5:
		return 5.5
	if road_class <= 9:
		return 4.5
	if road_class <= 12:
		return 3.5
	if road_class <= 14:
		return 3.0
	return 2.0

func _distance_to_segment(point: Vector2, a: Vector2, b: Vector2) -> float:
	var ab: Vector2 = b - a
	var length_squared: float = ab.length_squared()
	if length_squared <= 0.000001:
		return point.distance_to(a)
	var t: float = clampf((point - a).dot(ab) / length_squared, 0.0, 1.0)
	return point.distance_to(a + ab * t)
