class_name RoadSurfaceQuery
extends RefCounted

## Classifies world positions against authoritative BRT1 road centerlines using an in-memory spatial index.
##
## Dependencies:
## - Reads read-only LOD2 BRT1 runtime tiles generated by the world-data pipeline.
## - Uses the shared WorldCoordinates owner; has no rendering, vehicle, routing-policy, or SceneTree dependency.

const ROAD_MAGIC: String = "BRT1"
const ROAD: StringName = &"road"
const OFF_ROAD: StringName = &"off_road"
const QUERY_LOD: int = 2
const BIN_SIZE_M: float = 128.0
const INDEX_SAMPLE_STEP_M: float = BIN_SIZE_M * 0.5

var _world_dir: String = ""
var _world_coordinates
var _tile_cache: Dictionary = {}
var _perf_queries: int = 0
var _perf_segments_checked: int = 0
var _perf_index_entries: int = 0

func setup(world_dir: String, world_coordinates) -> void:
	_world_dir = world_dir
	_world_coordinates = world_coordinates
	_tile_cache.clear()
	_perf_queries = 0
	_perf_segments_checked = 0
	_perf_index_entries = 0

func surface_at(world_position: Vector3) -> StringName:
	if _world_coordinates == null or _world_dir.is_empty():
		return OFF_ROAD
	_perf_queries += 1
	var tile: Vector2i = _world_coordinates.world_to_tile(world_position)
	var absolute_position: Vector2 = _world_coordinates.world_to_absolute(world_position)
	for ty in range(tile.y - 1, tile.y + 2):
		for tx in range(tile.x - 1, tile.x + 2):
			if _tile_contains_road(Vector2i(tx, ty), absolute_position):
				return ROAD
	return OFF_ROAD

func consume_perf_metrics() -> Dictionary:
	var result := {
		"queries": _perf_queries,
		"segments_checked": _perf_segments_checked,
		"index_entries": _perf_index_entries,
	}
	_perf_queries = 0
	_perf_segments_checked = 0
	_perf_index_entries = 0
	return result

func _tile_contains_road(tile: Vector2i, absolute_position: Vector2) -> bool:
	var candidates: Array = _segments_for_point(tile, absolute_position)
	for segment_value in candidates:
		var segment: Dictionary = segment_value as Dictionary
		_perf_segments_checked += 1
		var a: Vector2 = segment["a"] as Vector2
		var b: Vector2 = segment["b"] as Vector2
		var half_width_m: float = float(segment["half_width_m"])
		if _distance_to_segment(absolute_position, a, b) <= half_width_m:
			return true
	return false

func _segments_for_point(tile: Vector2i, absolute_position: Vector2) -> Array:
	var tile_data: Dictionary = _tile_data(tile)
	var bins: Dictionary = tile_data["bins"] as Dictionary
	var origin: Vector2 = _world_coordinates.tile_origin_absolute(tile)
	var cell: Vector2i = _bin_for_point(absolute_position, origin)
	return bins.get(cell, []) as Array

func _tile_data(tile: Vector2i) -> Dictionary:
	if _tile_cache.has(tile):
		return _tile_cache[tile] as Dictionary
	var result := {"bins": {}}
	var bins: Dictionary = result["bins"] as Dictionary
	var path: String = "%s/lod%d/%d_%d.brtile" % [_world_dir, QUERY_LOD, tile.x, tile.y]
	if not FileAccess.file_exists(path):
		_tile_cache[tile] = result
		return result
	var file: FileAccess = FileAccess.open(path, FileAccess.READ)
	if file == null or file.get_length() < 8:
		_tile_cache[tile] = result
		return result
	if file.get_buffer(4).get_string_from_ascii() != ROAD_MAGIC:
		_tile_cache[tile] = result
		return result
	var count: int = file.get_32()
	var origin: Vector2 = _world_coordinates.tile_origin_absolute(tile)
	for _index in range(count):
		var road_class: int = file.get_8()
		var a := origin + Vector2(file.get_float(), file.get_float())
		var b := origin + Vector2(file.get_float(), file.get_float())
		var half_width_m := _road_half_width_m(road_class)
		var segment := {"a": a, "b": b, "half_width_m": half_width_m}
		_index_segment(bins, origin, segment)
	_tile_cache[tile] = result
	return result

func _index_segment(bins: Dictionary, origin: Vector2, segment: Dictionary) -> void:
	var a: Vector2 = segment["a"] as Vector2
	var b: Vector2 = segment["b"] as Vector2
	var half_width_m: float = float(segment["half_width_m"])
	var length_m := a.distance_to(b)
	var sample_count := maxi(1, ceili(length_m / INDEX_SAMPLE_STEP_M))
	var neighbor_radius := maxi(1, ceili(half_width_m / BIN_SIZE_M))
	var touched_cells: Dictionary = {}
	for sample_index in range(sample_count + 1):
		var t := float(sample_index) / float(sample_count)
		var center_cell := _bin_for_point(a.lerp(b, t), origin)
		for cell_y in range(center_cell.y - neighbor_radius, center_cell.y + neighbor_radius + 1):
			for cell_x in range(center_cell.x - neighbor_radius, center_cell.x + neighbor_radius + 1):
				var cell := Vector2i(cell_x, cell_y)
				if touched_cells.has(cell):
					continue
				touched_cells[cell] = true
				var bucket: Array = bins.get(cell, []) as Array
				bucket.append(segment)
				bins[cell] = bucket
				_perf_index_entries += 1

func _bin_for_point(point: Vector2, origin: Vector2) -> Vector2i:
	var local := point - origin
	return Vector2i(floori(local.x / BIN_SIZE_M), floori(local.y / BIN_SIZE_M))

func _road_half_width_m(road_class: int) -> float:
	if road_class <= 3:
		return 7.0
	if road_class <= 5:
		return 5.5
	if road_class <= 9:
		return 4.5
	if road_class <= 12:
		return 3.5
	if road_class <= 14:
		return 3.0
	return 2.0

func _distance_to_segment(point: Vector2, a: Vector2, b: Vector2) -> float:
	var ab: Vector2 = b - a
	var length_squared: float = ab.length_squared()
	if length_squared <= 0.000001:
		return point.distance_to(a)
	var t: float = clampf((point - a).dot(ab) / length_squared, 0.0, 1.0)
	return point.distance_to(a + ab * t)
