#!/usr/bin/env bash
set -euo pipefail
WORKTREE="${BRUR_PR_CHECK_WORKTREE:?}"; WORLD_DATA="${BRUR_PR_CHECK_WORLD_DATA:?}"; PYTHON="${PYTHON_BIN:?}"; GODOT="${GODOT_BIN:?}"; CHANGED_FILES="${BRUR_PR_CHECK_CHANGED_FILES:-}"; MANUAL_REVIEW="${BRUR_PR_CHECK_MANUAL_REVIEW:-none}"
CACHE="$WORKTREE/.poc_runtime/world_showcase"; RUNTIME_WORLD_DATA="$WORKTREE/.poc_runtime/pr_check_world_data"; TRAFFIC_INTERSECTION_DATA="$WORKTREE/.poc_runtime/traffic_intersections"
case "$MANUAL_REVIEW" in required|none) ;; *) printf 'PR_CHECK=FAIL invalid BRUR_PR_CHECK_MANUAL_REVIEW=%s\n' "$MANUAL_REVIEW" >&2; exit 70 ;; esac
scope_decision(){ local scope="$1" decision; decision="$(printf '%s\n' "$CHANGED_FILES" | "$PYTHON" "$WORKTREE/tools/pr_check_scope.py" "$scope")"; case "$decision" in required|skip) printf '%s\n' "$decision";; *) printf 'PR_CHECK=FAIL invalid %s scope decision: %s\n' "$scope" "$decision" >&2; return 70;; esac; }
ROUTE_GEOMETRY_SCOPE="$(scope_decision route-geometry)"; ROAD_LOD_SCOPE="$(scope_decision road-lod)"; CITY_LIGHT_SCOPE="$(scope_decision city-lights)"; WORLD_SHOWCASE_SCOPE="$(scope_decision world-showcase)"; BUILDING_TILE_SCOPE="$(scope_decision building-tiles)"
TRAFFIC_INTERSECTION_SCOPE=skip; DRIVING_VISUAL_SCOPE=skip; DRIVE_HUD_VISUAL_SCOPE=skip; GEODOT_POC_SCOPE=skip
printf '%s\n' "$CHANGED_FILES" | grep -Eq '(^|/)(traffic_intersections\.py|check_traffic_intersections_real_data\.py|test_traffic_intersections\.py)$' && TRAFFIC_INTERSECTION_SCOPE=required || true
printf '%s\n' "$CHANGED_FILES" | grep -Eq '^(harness/driving/|scripts/(route_driving_policy|vehicle_route_follower|vehicle_dynamics|player_vehicle|player_vehicle_controller)\.gd$|scenes/player_vehicle\.tscn$)' && DRIVING_VISUAL_SCOPE=required || true
printf '%s\n' "$CHANGED_FILES" | grep -Eq '^(scripts/(drive_hud|drive_hud_adapter|speed_limit_sign|road_speed_limit_query)\.gd|scenes/main\.tscn)$' && DRIVE_HUD_VISUAL_SCOPE=required || true
printf '%s\n' "$CHANGED_FILES" | grep -Eq '^(scripts/geodot_|scenes/geodot_poc\.tscn$|tests/godot/test_geodot_|tools/(setup_geodot_poc\.sh|check_geodot_gpkg\.py)$|\.github/workflows/geodot-poc-validation\.yml$)' && GEODOT_POC_SCOPE=required || true
[[ "$ROUTE_GEOMETRY_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_E6_BJARRED_ROUTE pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$ROAD_LOD_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_ROAD_LODS pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$CITY_LIGHT_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_CITY_LIGHT_REAL_DATA pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$WORLD_SHOWCASE_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_WORLD_SHOWCASE_PREP pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$BUILDING_TILE_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_BUILDING_MESH_LOD pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$TRAFFIC_INTERSECTION_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_TRAFFIC_INTERSECTIONS pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$DRIVING_VISUAL_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_DRIVING_VISUAL_REVIEW pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$DRIVE_HUD_VISUAL_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_DRIVE_HUD_VISUAL_REVIEW pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
[[ "$GEODOT_POC_SCOPE" == skip ]] && printf 'PR_CHECK=SKIP_GEODOT_POC pr=%s reason=unrelated-changes\n' "$BRUR_PR_CHECK_PR" || true
resolve_sweden_pbf(){ if [[ -n "${BRUR_WORLD_PBF:-}" ]]; then [[ -f "$BRUR_WORLD_PBF" ]] || return 1; printf '%s\n' "$BRUR_WORLD_PBF"; return; fi; local root candidate; root="$(cd "$(dirname "$WORLD_DATA")/.." && pwd)"; candidate="$(find "$root/syndicate/data" "$root/data" -maxdepth 1 -type f -name 'sweden-*.osm.pbf' -print 2>/dev/null | LC_ALL=C sort | tail -n1)"; [[ -n "$candidate" ]] || { printf 'PR_CHECK=FAIL required real-data rebuild needs Sweden PBF; set BRUR_WORLD_PBF\n' >&2; return 1; }; printf '%s\n' "$candidate"; }
resolve_geodot_gpkg(){ if [[ -n "${BRUR_GEODOT_GPKG:-}" ]]; then [[ -f "$BRUR_GEODOT_GPKG" ]] || return 1; printf '%s\n' "$BRUR_GEODOT_GPKG"; return; fi; local checkout_root checkout_parent mapped_root candidate root; checkout_root="$(cd "$(dirname "$WORLD_DATA")" && pwd)"; checkout_parent="$(cd "$checkout_root/.." && pwd)"; mapped_root="${BRUR_PR_CHECK_MAPPED_ROOT:-$checkout_root}"; for candidate in "$mapped_root/sweden-brur.gpkg" "$checkout_root/sweden-brur.gpkg" "$checkout_parent/sweden-brur.gpkg" "$checkout_parent/data/sweden-brur.gpkg" "$checkout_parent/brur-world/sweden-brur.gpkg"; do [[ -f "$candidate" ]] && { printf '%s\n' "$candidate"; return; }; done; for root in "$mapped_root" "$checkout_root" "$checkout_parent"; do [[ -d "$root" ]] || continue; candidate="$(find "$root" -maxdepth 3 -type f -name sweden-brur.gpkg -print 2>/dev/null | head -n1)"; [[ -n "$candidate" ]] && { printf '%s\n' "$candidate"; return; }; done; printf 'PR_CHECK=FAIL GeoDot POC requires sweden-brur.gpkg in the mapped BRUR checkout/data tree or BRUR_GEODOT_GPKG\n' >&2; return 1; }
ensure_routing_dataset_identity(){ "$PYTHON" "$WORKTREE/tools/check_routing_dataset.py" "$WORLD_DATA" && return; local pbf; pbf="$(resolve_sweden_pbf)"; "$PYTHON" "$WORKTREE/tools/build_routing_dataset.py" "$pbf" --output "$WORLD_DATA"; "$PYTHON" "$WORKTREE/tools/check_routing_dataset.py" "$WORLD_DATA"; }
prepare_traffic_intersection_data(){ [[ -f "$WORLD_DATA/traffic_signals.json" ]] && { printf '%s\n' "$WORLD_DATA"; return; }; local pbf; pbf="$(resolve_sweden_pbf)"; rm -rf "$TRAFFIC_INTERSECTION_DATA"; mkdir -p "$TRAFFIC_INTERSECTION_DATA"; ln -s "$WORLD_DATA/routing.brg" "$TRAFFIC_INTERSECTION_DATA/routing.brg"; "$PYTHON" "$WORKTREE/tools/build_traffic_signals.py" "$pbf" --output "$TRAFFIC_INTERSECTION_DATA" >&2; printf '%s\n' "$TRAFFIC_INTERSECTION_DATA"; }
prepare_road_runtime_data(){ local pbf entry name; pbf="$(resolve_sweden_pbf)"; rm -rf "$RUNTIME_WORLD_DATA"; mkdir -p "$RUNTIME_WORLD_DATA"; for entry in "$WORLD_DATA"/*; do name="$(basename "$entry")"; case "$name" in lod0|lod1|lod2|manifest.json) continue;; esac; ln -s "$entry" "$RUNTIME_WORLD_DATA/$name"; done; cp "$WORLD_DATA/manifest.json" "$RUNTIME_WORLD_DATA/manifest.json"; "$PYTHON" "$WORKTREE/tools/build_roads.py" "$pbf" --output "$RUNTIME_WORLD_DATA"; }
run_godot_test(){ local script="$1" marker="${2:-}" log status; log="$(mktemp "${TMPDIR:-/tmp}/brur-world-test.XXXXXX.log")"; set +e; "$GODOT" --headless --path "$WORKTREE" --script "$script" 2>&1 | tee "$log"; status=${PIPESTATUS[0]}; set -e; if [[ $status -ne 0 ]] || grep -Eq 'SCRIPT ERROR:|Failed to load script|test failed:' "$log"; then printf 'PR_CHECK=FAIL Godot reported script/test errors for %s\n' "$script" >&2; rm -f "$log"; return 1; fi; if [[ -n "$marker" ]] && ! grep -Fq "$marker" "$log"; then printf 'PR_CHECK=FAIL Godot test exited without required completion marker for %s: %s\n' "$script" "$marker" >&2; rm -f "$log"; return 1; fi; rm -f "$log"; }
[[ "$ROUTE_GEOMETRY_SCOPE" == required ]] && ensure_routing_dataset_identity
if [[ "$TRAFFIC_INTERSECTION_SCOPE" == required ]]; then data="$(prepare_traffic_intersection_data)"; "$PYTHON" "$WORKTREE/tools/check_traffic_intersections_real_data.py" "$data"; fi
if [[ "$BUILDING_TILE_SCOPE" == required ]]; then
  printf 'PR_CHECK=CHECK_BUILDING_ATOMIC_STREAM_HEADLESS pr=%s\n' "$BRUR_PR_CHECK_PR"; run_godot_test res://tests/godot/test_world_streaming_foundation.gd
  printf 'PR_CHECK=CHECK_BUILDING_REAL_DATA_PERFORMANCE pr=%s\n' "$BRUR_PR_CHECK_PR"; run_godot_test res://tests/godot/test_building_mesh_real_data.gd
  printf 'PR_CHECK=CHECK_MAP_CONTROLS_HEADLESS pr=%s\n' "$BRUR_PR_CHECK_PR"; run_godot_test res://tests/godot/test_map_controls.gd
  printf 'PR_CHECK=CHECK_PRODUCTION_DRIVE_FPS_REAL_DATA pr=%s targets=avg33.4ms-p95_50ms-worst250ms\n' "$BRUR_PR_CHECK_PR"; run_godot_test res://tests/godot/test_production_fps_real_data.gd 'production Drive FPS real-data test: OK'
fi
if [[ "$ROAD_LOD_SCOPE" == required ]]; then prepare_road_runtime_data; run_godot_test res://tests/godot/test_world_streaming_foundation.gd; run_godot_test res://tests/godot/test_road_surface_query_real_data.gd; fi
if [[ "$CITY_LIGHT_SCOPE" == required ]]; then "$PYTHON" "$WORKTREE/tools/build_city_light_density.py" "$WORLD_DATA"; GODOT_BIN="$GODOT" bash "$WORKTREE/tools/test_city_lights_real_data.sh"; fi
if [[ "$WORLD_SHOWCASE_SCOPE" == required ]]; then "$PYTHON" "$WORKTREE/tools/prepare_world_showcase.py" "$WORLD_DATA" --output "$CACHE"; run_godot_test res://tests/godot/test_world_showcase.gd; fi
GEODOT_GPKG=""
if [[ "$GEODOT_POC_SCOPE" == required ]]; then GEODOT_GPKG="$(resolve_geodot_gpkg)"; printf 'PR_CHECK=GEODOT_GPKG path=%s\n' "$GEODOT_GPKG"; bash "$WORKTREE/tools/setup_geodot_poc.sh"; "$PYTHON" "$WORKTREE/tools/check_geodot_gpkg.py" "$GEODOT_GPKG"; BRUR_GEODOT_GPKG="$GEODOT_GPKG" run_godot_test res://tests/godot/test_geodot_renderer_contracts.gd 'geodot renderer contracts: OK'; BRUR_GEODOT_GPKG="$GEODOT_GPKG" run_godot_test res://tests/godot/test_geodot_real_data.gd 'geodot real-data test: OK'; printf 'PR_CHECK=GEODOT_OBJECTIVE_OK pr=%s\n' "$BRUR_PR_CHECK_PR"; fi
if [[ "$MANUAL_REVIEW" == none && "$DRIVING_VISUAL_SCOPE" == skip && "$DRIVE_HUD_VISUAL_SCOPE" == skip ]]; then printf 'PR_CHECK=SKIP_VISUAL_REVIEW pr=%s reason=no-subjective-check-remains\n' "$BRUR_PR_CHECK_PR"; exit 0; fi
printf 'PR_CHECK=VISUAL_REVIEW pr=%s revision=%s\n' "$BRUR_PR_CHECK_PR" "$(git -C "$WORKTREE" rev-parse --short=12 HEAD)"
if [[ "$GEODOT_POC_SCOPE" == required ]]; then printf 'PR_CHECK=VISUAL_REVIEW_TARGET scene=scenes/geodot_poc.tscn reason=geodot-poc\n'; printf 'PR_CHECK=VISUAL_REVIEW_EXPECT window=production-main renderer=geodot area=Lund\n'; BRUR_GEODOT_GPKG="$GEODOT_GPKG" "$GODOT" --path "$WORKTREE" "$WORKTREE/scenes/geodot_poc.tscn"; exit; fi
if [[ "$DRIVE_HUD_VISUAL_SCOPE" == required ]]; then printf 'PR_CHECK=VISUAL_REVIEW_TARGET scene=scenes/main.tscn reason=drive-hud\n'; printf 'PR_CHECK=VISUAL_REVIEW_EXPECT window=production-main not=driving-harness\n'; "$GODOT" --path "$WORKTREE" "$WORKTREE/scenes/main.tscn"; exit; fi
if [[ "$DRIVING_VISUAL_SCOPE" == required ]]; then printf 'PR_CHECK=VISUAL_REVIEW_TARGET scene=harness/driving/driving_harness.tscn reason=driving-feel\n'; "$GODOT" --path "$WORKTREE" "$WORKTREE/harness/driving/driving_harness.tscn"; exit; fi
if [[ "$MANUAL_REVIEW" == required && "$BUILDING_TILE_SCOPE" == skip && "$ROAD_LOD_SCOPE" == skip && "$CITY_LIGHT_SCOPE" == skip && "$WORLD_SHOWCASE_SCOPE" == skip ]]; then printf 'PR_CHECK=VISUAL_REVIEW_TARGET scene=scenes/main.tscn reason=pr-merge-decision\n'; printf 'PR_CHECK=VISUAL_REVIEW_EXPECT window=production-main not=editor\n'; "$GODOT" --path "$WORKTREE" "$WORKTREE/scenes/main.tscn"; exit; fi
"$GODOT" --path "$WORKTREE"
