#!/usr/bin/env bash
set -euo pipefail
WORKTREE="${BRUR_PR_CHECK_WORKTREE:?}"; WORLD_DATA="${BRUR_PR_CHECK_WORLD_DATA:?}"; PYTHON="${PYTHON_BIN:?}"; GODOT="${GODOT_BIN:?}"; MANUAL_REVIEW="${BRUR_PR_CHECK_MANUAL_REVIEW:-none}"; CHANGED_FILES="${BRUR_PR_CHECK_CHANGED_FILES:-}"
if ! printf '%s\n' "$CHANGED_FILES" | grep -Eq '(^|/)(geodot[^/]*|test_geodot[^/]*)'; then exec bash "$WORKTREE/tools/pr_check_standard.sh"; fi
run_stage(){ local stage="$1"; shift; local status=0; printf 'PR_CHECK=STAGE_BEGIN stage=%s pr=%s\n' "$stage" "$BRUR_PR_CHECK_PR"; "$@" || status=$?; if [[ $status -eq 0 ]]; then printf 'PR_CHECK=STAGE_OK stage=%s pr=%s\n' "$stage" "$BRUR_PR_CHECK_PR"; return 0; fi; printf 'PR_CHECK=STAGE_FAIL stage=%s pr=%s status=%s\n' "$stage" "$BRUR_PR_CHECK_PR" "$status" >&2; return "$status"; }
run_godot_test(){ local script="$1" marker="${2:-}" log status; log="$(mktemp "${TMPDIR:-/tmp}/brur-geodot-test.XXXXXX.log")"; set +e; "$GODOT" --headless --path "$WORKTREE" --script "$script" 2>&1 | tee "$log"; status=${PIPESTATUS[0]}; set -e; if [[ $status -ne 0 ]] || grep -Eq 'SCRIPT ERROR:|Failed to load script|ASSERT FAILED:|test failed:' "$log"; then printf 'PR_CHECK=FAIL Godot failed clean-exit test %s status=%s\n' "$script" "$status" >&2; rm -f "$log"; return 1; fi; if [[ -n "$marker" ]] && ! grep -Fq "$marker" "$log"; then printf 'PR_CHECK=FAIL missing completion marker for %s: %s\n' "$script" "$marker" >&2; rm -f "$log"; return 1; fi; rm -f "$log"; }
resolve_gpkg(){ local candidate; for candidate in "${BRUR_GEODOT_GPKG:-}" "$WORLD_DATA/../sweden-brur.gpkg" "$(dirname "$WORLD_DATA")/sweden-brur.gpkg" "$HOME/Dropbox/Code/brur-world/sweden-brur.gpkg"; do [[ -n "$candidate" && -f "$candidate" ]] && { printf '%s\n' "$candidate"; return 0; }; done; candidate="$(find "$(dirname "$WORLD_DATA")" "$HOME/Dropbox/Code" -maxdepth 4 -type f -name 'sweden-brur.gpkg' -print 2>/dev/null | head -n1 || true)"; [[ -n "$candidate" ]] || { printf 'PR_CHECK=FAIL sweden-brur.gpkg not found\n' >&2; return 1; }; printf '%s\n' "$candidate"; }
GPKG="$(resolve_gpkg)"; export BRUR_GEODOT_GPKG="$GPKG"; export BRUR_GEODOT_FAR_CACHE="$WORKTREE/.cache/geodot-far-cache.json"; printf 'PR_CHECK=GEODOT_GPKG path=%s\n' "$GPKG"
run_stage geodot-setup bash "$WORKTREE/tools/setup_geodot_poc.sh"; [[ -s "$BRUR_GEODOT_FAR_CACHE" ]] || { printf 'PR_CHECK=FAIL far cache missing after setup\n' >&2; exit 1; }
run_stage geodot-gpkg-contract "$PYTHON" "$WORKTREE/tools/check_geodot_gpkg.py" "$GPKG"; run_stage geodot-far-cache-contract "$PYTHON" "$WORKTREE/tests/test_geodot_far_cache.py"
for spec in 'geodot-renderer-contracts|res://tests/godot/test_geodot_renderer_contracts.gd|' 'geodot-runtime-bounds|res://tests/godot/test_geodot_runtime_bounds.gd|geodot runtime bounds: OK' 'geodot-lod-policy|res://tests/godot/test_geodot_lod_policy.gd|GEODOT_LOD_POLICY=PASS' 'geodot-tuning-contract|res://tests/godot/test_geodot_tuning_contract.gd|GEODOT_TUNING_CONTRACT=PASS' 'geodot-view-coverage|res://tests/godot/test_geodot_view_coverage.gd|' 'geodot-streaming-policy|res://tests/godot/test_geodot_streaming_policy.gd|' 'geodot-streaming-transition|res://tests/godot/test_geodot_streaming_transition.gd|' 'geodot-cell-geometry|res://tests/godot/test_geodot_cell_geometry.gd|' 'geodot-lod-continuity|res://tests/godot/test_geodot_lod_continuity.gd|' 'geodot-composition|res://tests/godot/test_geodot_composition_contract.gd|' 'geodot-failure-contract|res://tests/godot/test_geodot_failure_contract.gd|' 'geodot-real-data|res://tests/godot/test_geodot_real_data.gd|geodot real-data test: OK' 'geodot-fps-real-data|res://tests/godot/test_geodot_fps_real_data.gd|GeoDot Drive FPS real-data test: OK'; do IFS='|' read -r stage script marker <<< "$spec"; run_stage "$stage" run_godot_test "$script" "$marker"; done
printf 'PR_CHECK=GEODOT_OBJECTIVE_OK pr=%s clean_exit=true bounded_pipeline=true far_cache=true screen_space_lod=true tuning_log=true frame_budget=true ram_budget=true\n' "$BRUR_PR_CHECK_PR"
if [[ "$MANUAL_REVIEW" != "required" ]]; then printf 'PR_CHECK=SKIP_VISUAL_REVIEW pr=%s reason=no-subjective-check-remains\n' "$BRUR_PR_CHECK_PR"; exit 0; fi
printf 'PR_CHECK=VISUAL_REVIEW pr=%s revision=%s\n' "$BRUR_PR_CHECK_PR" "$(git -C "$WORKTREE" rev-parse --short=12 HEAD)"; printf 'PR_CHECK=VISUAL_REVIEW_TARGET scene=scenes/geodot_poc.tscn reason=geodot-perceptual-tuning\n'; printf 'PR_CHECK=VISUAL_REVIEW_INSTRUCTION tune 500km->300km->75km->6km->3km; use ? help; judge city signal, seamless refinement and 3D onset; tuning/performance JSONL is persisted automatically\n'
BRUR_BUILD_REVISION="$(git -C "$WORKTREE" rev-parse --short=12 HEAD)" BRUR_GEODOT_GPKG="$GPKG" BRUR_GEODOT_FAR_CACHE="$BRUR_GEODOT_FAR_CACHE" "$GODOT" --path "$WORKTREE" "$WORKTREE/scenes/geodot_poc.tscn"
